# Generated by Django 4.2.9 on 2024-02-16 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makeover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('service_type', models.IntegerField(choices=[(0, 'Makeup'), (1, 'Hair')])),
                ('start_time', models.TimeField(choices=[(datetime.time(8, 30), '8:30am'), (datetime.time(9, 0), '9:00am'), (datetime.time(9, 30), '9:30am'), (datetime.time(10, 0), '10:00am'), (datetime.time(10, 30), '10:30am'), (datetime.time(11, 0), '11:00am'), (datetime.time(11, 30), '11:30am'), (datetime.time(12, 0), '12:00pm'), (datetime.time(12, 30), '12:30pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(13, 30), '1:30pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(14, 30), '2:30pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(15, 30), '3:30pm'), (datetime.time(16, 0), '4:00pm'), (datetime.time(16, 30), '4:30pm')])),
                ('confirmed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_booking', 'start_time'],
            },
        ),
    ]
